### ISSUE TITLE
cdmat creation

### ISSUE THREAD

**Issue by Brooklyn1995** [kosukeimai/redist#13]
Hello!

I want to try the algorithm with my own redistricting plan, but how can I generate the matrix of every possible partition of precints (cdmat) beforehand?

**Comment by bfifield** [comment]
Hi @Brooklyn1995 - could you clarify a bit more about what you're looking for? Are you looking to use your redistricting plan as the starting plan for the MCMC algorithm (using `redist.mcmc()`), or are you looking to enumerate every possible partition of your precinct map into K districts (using `redist.enumerate()`)?

**Comment by kosukeimai** [comment]
No follow-up and so I'm closing this.
