### ISSUE TITLE
redist.findparams error

### ISSUE THREAD

**Issue by Lafoley** [kosukeimai/redist#8]
Hello, when I try to run your example code for redist.findparams on a windows computer with R version 3.4.1 I get an error.

##Code:
require(redist)
data(algdat.pfull)

set.seed(1)
initcds <- algdat.pfull$cdmat[,sample(1:ncol(algdat.pfull$cdmat), 1)]

params <- expand.grid(eprob = c(.01, .05, .1))

redist.findparams(adjobj = algdat.pfull$adjlist,
                  popvec = algdat.pfull$precinct.data$pop,
                  initcds = initcds, nsims = 10000, params = params)

##Error:
Error in swMH(aList = preprocout$data$adjlist, cdvec = cds, cdorigvec = preprocout$data$initcds,  : 
  Expecting a single value: [extent=0].

Thank you,
Lauren

**Comment by christopherkenny** [comment]
Closed by #32
